### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yakexi007** [fidyeates/PyHighcharts#20]
# python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from PyHighcharts import Highchart
  File "/mnt/test/PyHighcharts/__init__.py", line 1, in <module>
    from highcharts.chart import Highchart, set_temp_dir
  File "/mnt/test/PyHighcharts/highcharts/chart.py", line 271
    for k, opClass in bind}
      ^
SyntaxError: invalid syntax

**Comment by fidyeates** [comment]
Hi @yakexi007 

What version of python are you using, if it is throwing an error on a dictionary comprehension then it might be because of Python 2.6 or earlier. 

If this is the case, you could try checkout out the dev branch (https://github.com/fidyeates/PyHighcharts/tree/dev), as far as I'm aware that doesn't use any dict or list comprehensions so it has a greater chance of being compatible.

However, that said I haven't gotten around to testing on 2.6 yet, so that is just a guess.

**Comment by yakexi007** [comment]
Thanks fidyeates.  The problem solved.
